[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "outparse"
version = "1.0.4"
description = "OutParse — configurable fast printout/text table parser"
readme = "README.md"
license = {file = "LICENSE"}
authors = [
    {name = "edmynay"}
]
requires-python = ">=3.8"
keywords = [
    "parse",
    "parser",
    "text parser",
    "text table",
    "printout parser",
    "cli output",
    "cli parser",
    "structured text",
    "table parser",
    "terminal output",
    "console output",
    "network printout",
    "telecom parser",
    "telecom printout",
    "text processing",
    "data extraction"
]


classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent"
]

[project.urls]
Homepage = "https://github.com/edmynay/outparse"
Repository = "https://github.com/edmynay/outparse"
Issues = "https://github.com/edmynay/outparse/issues"
Documentation = "https://github.com/edmynay/outparse#readme"
Author = "https://www.linkedin.com/in/dmytro-naichuk/"

[tool.setuptools.packages.find]
include = ["outparse*"]